import type { NextPage } from 'next'
import Head from 'next/head'
import useAuth from 'hooks/useAuth'
import { Box, Heading } from '@chakra-ui/react'

const Home: NextPage = () => {

  const { user, signin } = useAuth()

  return (
    <Box bg="gray.100" w="100%" p={4}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <Heading as='h2' size='3xl' noOfLines={1}>
        Aprenda programação direto ao ponto
      </Heading>

    </Box>
  )
}

export default Home
