import type { NextPage } from 'next'
import Head from 'next/head'
import useAuth from 'hooks/useAuth'
import Layout from 'components/Layout'
import { Box, Flex, Heading, Text, Button, Wrap } from '@chakra-ui/react'

import { getAllTechnologies } from 'lib/datocms'
import LogoInterface from 'interfaces/Logos'

const Cover: React.FC<{ technologies: LogoInterface }> = ({ technologies }) => {

  const bgColor = '#FFF'
  
  return (
    <Box bgColor={bgColor}>
      <Flex justifyContent="center" alignItems="center" py={20}>
        <Flex px={[4, 8]} py={[0, 20]} w="full" maxW="1200px" direction="column">
          <Heading
            as="h1"
            fontSize={{ base: '42px', md: '52px', lg: '72px' }}
            mb={4}
            fontWeight="xBold">
            Aprenda programação
            <Box>direto ao ponto </Box>
            <Box bgGradient="linear(to-l, #7928CA,#FF0080)" bgClip="text">
              100% free.
            </Box>
          </Heading>
          <Text fontSize={{ base: '16px', md: '20px', lg: '22px' }}>
            <Box>
              Mantenha seus conhecimentos atualizados com as mais novas{' '}
            </Box>
            <Box>tecnologias que estão disponíveis no mercado!</Box>
          </Text>
          <Box>
            <Button
              as="a"
              my={10}
              colorScheme="purple"
              variant="outline"
              size="lg"
              href="#series"
            >
              Bora começar!
            </Button>
          </Box>

          {technologies.map((item) => (
            <></>
          ))}

          <Box>
            <Wrap>
              
            </Wrap>
          </Box>
        </Flex>
      </Flex>
    </Box>
  )
}

const Home: NextPage<{ technologies: LogoInterface[] }> = ({ technologies }) => {

  const { user, signin } = useAuth()

  return (
    <Layout>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <Cover technologies={technologies} />

    </Layout>
  )
}

export const getStaticProps = async () => {

  const technologies = await getAllTechnologies()

  return {
    props: {
      technologies
    },
    revalidate: 120 // segundos
  }
}

export default Home
