import type { NextPage } from 'next'
import Head from 'next/head'
import useAuth from 'hooks/useAuth'

const Home: NextPage = () => {

  const { user, signin } = useAuth()
  console.log('user', user)

  return (
    <div>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <button onClick={() => signin?.()}>Logar</button>

    </div>
  )
}

export default Home
